In [1]:
from ndpi.visualization.tables import fix_gt_table

from ech_discovery.notebook import *

# Load data

In [2]:
df_versions = pl.read_csv(
    config.INTERIM_DATA_DIR / "webserver-versions.tsv",
    separator="\t",
    infer_schema_length=None,
)

In [3]:
df = (
    pl.read_csv(config.INTERIM_DATA_DIR / "tls-attacker-results.tsv", separator="\t")
    .join(df_versions, on=[C.server, C.version], how="left", validate="m:1")
    .with_columns(
        pl.col(C.server).replace("apache", Strings.apache_httpd),
    )
)
assert (
    df[C.released].null_count() == 0
), f"unmatched versions: {df.filter(pl.col(C.released).is_null()).select(C.server, C.version).rows()}"
with pl.Config(tbl_rows=50):
    display(df)

shape: (24, 10)
┌────────┬─────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ server ┆ version ┆ variant    ┆ TLS-grease ┆ … ┆ unparsable ┆ verdict    ┆ released  ┆ source    │
│ ---    ┆ ---     ┆ ---        ┆ ---        ┆   ┆ -ech-as-ra ┆ ---        ┆ ---       ┆ ---       │
│ str    ┆ str     ┆ str        ┆ str        ┆   ┆ w-extensio ┆ str        ┆ str       ┆ str       │
│        ┆         ┆            ┆            ┆   ┆ …          ┆            ┆           ┆           │
│        ┆         ┆            ┆            ┆   ┆ ---        ┆            ┆           ┆           │
│        ┆         ┆            ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞════════╪═════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ Apache ┆ 2.4.67  ┆ base       ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2026-05-0 ┆ https://a │
│ httpd  ┆         ┆            ┆            ┆   ┆            ┆ ECH-aware  ┆ 4         ┆ rchive.ap │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ ache.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ dis…      │
│ Apache ┆ trunk   ┆ ech        ┆ -          ┆ … ┆ decode_err ┆ ECH-aware  ┆ 2026-03-2 ┆ defo-proj │
│ httpd  ┆         ┆            ┆            ┆   ┆ or         ┆ (rejects   ┆ 3         ┆ ect/apach │
│        ┆         ┆            ┆            ┆   ┆            ┆ 0xFE0D     ┆           ┆ e-httpd   │
│        ┆         ┆            ┆            ┆   ┆            ┆ with…      ┆           ┆ trun…     │
│ Apache ┆ trunk   ┆ ech-disabl ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2026-03-2 ┆ defo-proj │
│ httpd  ┆         ┆ ed         ┆            ┆   ┆            ┆ ECH-aware  ┆ 3         ┆ ect/apach │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ e-httpd   │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ trun…     │
│ nginx  ┆ 1.21.0  ┆ base       ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2021-05-2 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆            ┆ ECH-aware  ┆ 5         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.22.0  ┆ base       ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2022-05-2 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆            ┆ ECH-aware  ┆ 4         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.24.0  ┆ base       ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2023-04-1 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆            ┆ ECH-aware  ┆ 1         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.26.0  ┆ base       ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2024-04-2 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆            ┆ ECH-aware  ┆ 3         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.27.0  ┆ base       ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2024-05-2 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆            ┆ ECH-aware  ┆ 9         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.28.0  ┆ base       ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2025-04-2 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆            ┆ ECH-aware  ┆ 3         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.29.4  ┆ base       ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2025-12-0 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆            ┆ ECH-aware  ┆ 9         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.29.4  ┆ boringssl  ┆ -          ┆ … ┆ decode_err ┆ ECH NEVER  ┆ 2025-12-0 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆ or         ┆ ENABLED on ┆ 9         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆ BoringSSL… ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.29.4  ┆ boringssl- ┆ -          ┆ … ┆ decode_err ┆ ECH-aware  ┆ 2025-12-0 ┆ https://n │
│        ┆         ┆ disabled   ┆            ┆   ┆ or         ┆ (rejects   ┆ 9         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆ 0xFE0D     ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆ with…      ┆           ┆ S (…      │
│ nginx  ┆ 1.29.4  ┆ ech        ┆ -          ┆ … ┆ decode_err ┆ ECH-aware  ┆ 2025-12-0 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆ or         ┆ (rejects   ┆ 9         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆ 0xFE0D     ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆ with…      ┆           ┆ S (…      │
│ nginx  ┆ 1.29.4  ┆ ech-disabl ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2025-12-0 ┆ https://n │
│        ┆         ┆ ed         ┆            ┆   ┆            ┆ ECH-aware  ┆ 9         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.30.0  ┆ base       ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2026-04-1 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆            ┆ ECH-aware  ┆ 4         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.30.0  ┆ boringssl  ┆ -          ┆ … ┆ decode_err ┆ ECH NEVER  ┆ 2026-04-1 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆ or         ┆ ENABLED on ┆ 4         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆ BoringSSL… ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.30.0  ┆ boringssl- ┆ -          ┆ … ┆ decode_err ┆ ECH-aware  ┆ 2026-04-1 ┆ https://n │
│        ┆         ┆ disabled   ┆            ┆   ┆ or         ┆ (rejects   ┆ 4         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆ 0xFE0D     ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆ with…      ┆           ┆ S (…      │
│ nginx  ┆ 1.30.0  ┆ ech        ┆ -          ┆ … ┆ decode_err ┆ ECH-aware  ┆ 2026-04-1 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆ or         ┆ (rejects   ┆ 4         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆ 0xFE0D     ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆ with…      ┆           ┆ S (…      │
│ nginx  ┆ 1.30.0  ┆ ech-disabl ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2026-04-1 ┆ https://n │
│        ┆         ┆ ed         ┆            ┆   ┆            ┆ ECH-aware  ┆ 4         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.31.0  ┆ base       ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2026-05-1 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆            ┆ ECH-aware  ┆ 3         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.31.0  ┆ boringssl  ┆ -          ┆ … ┆ decode_err ┆ ECH NEVER  ┆ 2026-05-1 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆ or         ┆ ENABLED on ┆ 3         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆ BoringSSL… ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
│ nginx  ┆ 1.31.0  ┆ boringssl- ┆ -          ┆ … ┆ decode_err ┆ ECH-aware  ┆ 2026-05-1 ┆ https://n │
│        ┆         ┆ disabled   ┆            ┆   ┆ or         ┆ (rejects   ┆ 3         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆ 0xFE0D     ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆ with…      ┆           ┆ S (…      │
│ nginx  ┆ 1.31.0  ┆ ech        ┆ -          ┆ … ┆ decode_err ┆ ECH-aware  ┆ 2026-05-1 ┆ https://n │
│        ┆         ┆            ┆            ┆   ┆ or         ┆ (rejects   ┆ 3         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆ 0xFE0D     ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆ with…      ┆           ┆ S (…      │
│ nginx  ┆ 1.31.0  ┆ ech-disabl ┆ -          ┆ … ┆ -          ┆ Not        ┆ 2026-05-1 ┆ https://n │
│        ┆         ┆ ed         ┆            ┆   ┆            ┆ ECH-aware  ┆ 3         ┆ ginx.org/ │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ en/CHANGE │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆           ┆ S (…      │
└────────┴─────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

# Table output

In [4]:
df_gt = (
    df.sort(C.server, C.version, C.variant)
    .with_columns(
        (
            pl.when(pl.col(C.variant).str.contains("ech"))
            .then(pl.lit(Strings.openssl3_ech))
            .when(pl.col(C.variant).str.contains("base"))
            .then(pl.lit(Strings.openssl3))
            .when(pl.col(C.variant).str.contains("boring"))
            .then(pl.lit(Strings.boringssl))
        ).alias(Strings.tls_library),
        (
            pl.when(pl.col(C.variant).str.contains("disabled|base"))
            .then(pl.lit("-"))
            .when(pl.col(C.variant).is_in(["ech", "boringssl"]))
            .then(pl.lit("x"))
            .alias(Strings.ech_configured)
        ),
        pl.when(pl.col(C.unparsable_ech_extension) != "-")
        .then(pl.lit("x"))
        .fill_null("-")
        .alias(Strings.niere_et_al),
        pl.when(pl.col(C.parsable_ech_extension) != "-")
        .then(pl.lit("x"))
        .fill_null("-")
        .alias(Strings.this_work),
        (
            pl.when(
                pl.col(C.variant).str.contains("ech")
                | pl.col(C.variant).str.contains("boringssl")
            ).then(pl.lit("x"))
        )
        .fill_null("-")
        .alias(Strings.code_support),
    )
    .filter(~(pl.col(C.variant) == "boringssl"))
    .select(
        Strings.tls_library,
        C.server,
        C.version,
        C.released,
        Strings.code_support,
        Strings.ech_configured,
        C.niere_unknown_extension,
        C.unparsable_ech_extension,
        C.parsable_ech_extension,
        Strings.niere_et_al,
        Strings.this_work,
        C.verdict,
    )
    .rename(
        {
            C.niere_unknown_extension: Strings.niere_unknown_extension,
            C.unparsable_ech_extension: Strings.unparsable_ech_extension,
            C.parsable_ech_extension: Strings.parsable_ech_extension,
            C.server: Strings.webserver,
            C.version: Strings.version,
            C.verdict: Strings.result,
            C.released: Strings.released,
        }
    )
    .sort(Strings.tls_library, Strings.webserver, Strings.version, Strings.code_support)
)
df_gt

shape: (21, 12)
┌────────────┬───────────┬─────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ TLS        ┆ Webserver ┆ Version ┆ Released  ┆ … ┆ Parsable  ┆ Niere et  ┆ This Work ┆ Result    │
│ library    ┆ ---       ┆ ---     ┆ ---       ┆   ┆ ECH       ┆ al.       ┆ ---       ┆ ---       │
│ ---        ┆ str       ┆ str     ┆ str       ┆   ┆ extension ┆ ---       ┆ str       ┆ str       │
│ str        ┆           ┆         ┆           ┆   ┆ (this w…  ┆ str       ┆           ┆           │
│            ┆           ┆         ┆           ┆   ┆ ---       ┆           ┆           ┆           │
│            ┆           ┆         ┆           ┆   ┆ str       ┆           ┆           ┆           │
╞════════════╪═══════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ BoringSSL  ┆ nginx     ┆ 1.29.4  ┆ 2025-12-0 ┆ … ┆ -         ┆ x         ┆ -         ┆ ECH-aware │
│            ┆           ┆         ┆ 9         ┆   ┆           ┆           ┆           ┆ (rejects  │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 0xFE0D    │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ with…     │
│ BoringSSL  ┆ nginx     ┆ 1.30.0  ┆ 2026-04-1 ┆ … ┆ -         ┆ x         ┆ -         ┆ ECH-aware │
│            ┆           ┆         ┆ 4         ┆   ┆           ┆           ┆           ┆ (rejects  │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 0xFE0D    │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ with…     │
│ BoringSSL  ┆ nginx     ┆ 1.31.0  ┆ 2026-05-1 ┆ … ┆ -         ┆ x         ┆ -         ┆ ECH-aware │
│            ┆           ┆         ┆ 3         ┆   ┆           ┆           ┆           ┆ (rejects  │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 0xFE0D    │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ with…     │
│ …          ┆ …         ┆ …       ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ OpenSSL3   ┆ nginx     ┆ 1.31.0  ┆ 2026-05-1 ┆ … ┆ unk-ee    ┆ x         ┆ x         ┆ ECH-aware │
│ with ECH   ┆           ┆         ┆ 3         ┆   ┆           ┆           ┆           ┆ (rejects  │
│ (defo      ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 0xFE0D    │
│ fork)      ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ with…     │
│ OpenSSL3   ┆ nginx     ┆ 1.31.0  ┆ 2026-05-1 ┆ … ┆ -         ┆ -         ┆ -         ┆ Not       │
│ with ECH   ┆           ┆         ┆ 3         ┆   ┆           ┆           ┆           ┆ ECH-aware │
│ (defo      ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆           │
│ fork)      ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴─────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
def add_group_midrules(latex: str, group_values: list) -> str:
    lines = latex.split("\n")
    bottomrule_idx = next(
        i for i, l in enumerate(lines) if l.strip().startswith(r"\bottomrule")
    )
    body_start = max(i for i in range(bottomrule_idx) if r"\midrule" in lines[i])
    body_lines = lines[body_start + 1 : bottomrule_idx]

    assert len(body_lines) == len(
        group_values
    ), f"Row count mismatch: {len(body_lines)} body lines vs {len(group_values)} group values"

    new_body = []
    for i, (line, val) in enumerate(zip(body_lines, group_values)):
        new_body.append(line)
        is_last_row = i == len(group_values) - 1
        if not is_last_row and val != group_values[i + 1]:
            new_body.append(r"\midrule")

    lines[body_start + 1 : bottomrule_idx] = new_body
    return "\n".join(lines)

In [6]:
cols = df_gt.columns
title = """
Apache httpd and nginx tested with TLS Attacker reproducing the evaluation of Niere et al.
TLS Attacker correctly determines code support for BoringSSL.
With OpenSSL, ECH is not detected by Niere et al. due to OpenSSL ignoring errors in used ECH extensions.
Our work does not detect code support, but whether ECH is configured or not.
We do not test BoringSSL builds with ECH configured, because the webservers lack the respective bindings for BoringSSL.
"""

ECH_DETECTED_SYMBOL = {"x": Strings.latex_cmark.value, "-": Strings.latex_xmark.value}
ECH_DETECTED_COLS = [
    Strings.code_support,
    Strings.ech_configured,
    Strings.niere_et_al,
    Strings.this_work,
]

gt = (
    GT(df_gt.drop(cols[6:9] + [Strings.result]))
    .tab_spanner(label=Strings.server_configuration, columns=cols[:6])
    .tab_spanner(label=Strings.ech_detected, columns=cols[9:11])
    .tab_header(title=title)
    .fmt(fns=lambda x: ECH_DETECTED_SYMBOL[x], columns=ECH_DETECTED_COLS)
    .fmt(
        fns=lambda x: x.replace("(defo fork)", r"\cite{d-o-23}"),
        columns=Strings.tls_library,
    )
    .fmt(
        fns=lambda x: x.replace("trunk", r"trunk \cite{d-a-23}"),
        columns=Strings.version,
    )
    .cols_align(align="center", columns=ECH_DETECTED_COLS)
)
display(gt)
print(
    add_group_midrules(
        fix_gt_table(gt.as_latex(), "tab:tls-attacker-nginx-httpd"),
        df_gt[Strings.tls_library].to_list(),
    )
)

GT(_tbl_data=shape: (21, 8)
┌───────────────┬───────────┬─────────┬────────────┬─────────┬──────────────┬──────────┬───────────┐
│ TLS library   ┆ Webserver ┆ Version ┆ Released   ┆ Code    ┆ ECH          ┆ Niere et ┆ This Work │
│ ---           ┆ ---       ┆ ---     ┆ ---        ┆ Support ┆ Configured   ┆ al.      ┆ ---       │
│ str           ┆ str       ┆ str     ┆ str        ┆ ---     ┆ ---          ┆ ---      ┆ str       │
│               ┆           ┆         ┆            ┆ str     ┆ str          ┆ str      ┆           │
╞═══════════════╪═══════════╪═════════╪════════════╪═════════╪══════════════╪══════════╪═══════════╡
│ BoringSSL     ┆ nginx     ┆ 1.29.4  ┆ 2025-12-09 ┆ x       ┆ -            ┆ x        ┆ -         │
│ BoringSSL     ┆ nginx     ┆ 1.30.0  ┆ 2026-04-14 ┆ x       ┆ -            ┆ x        ┆ -         │
│ BoringSSL     ┆ nginx     ┆ 1.31.0  ┆ 2026-05-13 ┆ x       ┆ -            ┆ x        ┆ -         │
│ …             ┆ …         ┆ …       ┆ …          ┆ …       ┆ …            ┆ …        ┆ …         │
│ OpenSSL3 with ┆ nginx     ┆ 1.31.0  ┆ 2026-05-13 ┆ x       ┆ x            ┆ x        ┆ x         │
│ ECH (defo     ┆           ┆         ┆            ┆         ┆              ┆          ┆           │
│ fork)         ┆           ┆         ┆            ┆         ┆              ┆          ┆           │
│ OpenSSL3 with ┆ nginx     ┆ 1.31.0  ┆ 2026-05-13 ┆ x       ┆ -            ┆ -        ┆ -         │
│ ECH (defo     ┆           ┆         ┆            ┆         ┆              ┆          ┆           │
│ fork)         ┆           ┆         ┆            ┆         ┆              ┆          ┆           │
└───────────────┴───────────┴─────────┴────────────┴─────────┴──────────────┴──────────┴───────────┘, _body=<great_tables._gt_data.Body object at 0x76d98013fcb0>, _boxhead=Boxhead([ColInfo(var='TLS library', type=<ColInfoTypeEnum.default: 1>, column_label='TLS library', column_align='left', column_width=None), ColInfo(var='Webserver', type=<ColInfoTypeEnum.default: 1>, column_label='Webserver', column_align='left', column_width=None), ColInfo(var='Version', type=<ColInfoTypeEnum.default: 1>, column_label='Version', column_align='left', column_width=None), ColInfo(var='Released', type=<ColInfoTypeEnum.default: 1>, column_label='Released', column_align='left', column_width=None), ColInfo(var='Code Support', type=<ColInfoTypeEnum.default: 1>, column_label='Code Support', column_align='center', column_width=None), ColInfo(var='ECH Configured', type=<ColInfoTypeEnum.default: 1>, column_label='ECH Configured', column_align='center', column_width=None), ColInfo(var='Niere et al.', type=<ColInfoTypeEnum.default: 1>, column_label='Niere et al.', column_align='center', column_width=None), ColInfo(var='This Work', type=<ColInfoTypeEnum.default: 1>, column_label='This Work', column_align='center', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x76d98013f8c0>, _spanners=Spanners([SpannerInfo(spanner_id=<Strings.server_configuration: 'Server Configuration'>, spanner_level=0, spanner_label='Server Configuration', spanner_units=None, spanner_pattern=None, vars=['TLS library', 'Webserver', 'Version', 'Released', 'Code Support', 'ECH Configured'], built=None), SpannerInfo(spanner_id=<Strings.ech_detected: 'ECH Detected'>, spanner_level=0, spanner_label='ECH Detected', spanner_units=None, spanner_pattern=None, vars=['Niere et al.', 'This Work'], built=None)]), _heading=Heading(title='\nApache httpd and nginx tested with TLS Attacker reproducing the evalation of Niere et al.\nTLS Attacker correctly determines code support for BoringSSL.\nWith OpenSSL ECH is not detected by Niere et al. due to OpenSSL ignoring errors in used ECH extensions.\nOur work does not detect code support, but whether ECH is configured or not.\nWe do not test BoringSSL builds with ECH configured, because the webservers lack the respective bindings for BoringSSL.\n', subtitle=None, preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x76d973fbc1a0>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x76d9801ea0d0>, _source_notes=[], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x76d973fbc2f0>, _formats=[<great_tables._gt_data.FormatInfo object at 0x76d98013fe00>, <great_tables._gt_data.FormatInfo object at 0x76d9801ea210>, <great_tables._gt_data.FormatInfo object at 0x76d9801ea990>], _substitutions=[], _col_merge=[], _transforms=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='center'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value=None), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), summary_row_padding=OptionsInfo(scss=True, category='summary_row', type='px', value='8px'), summary_row_padding_horizontal=OptionsInfo(scss=True, category='summary_row', type='px', value='5px'), summary_row_background_color=OptionsInfo(scss=True, category='summary_row', type='value', value=None), summary_row_text_transform=OptionsInfo(scss=True, category='summary_row', type='value', value='inherit'), summary_row_border_style=OptionsInfo(scss=True, category='summary_row', type='value', value='solid'), summary_row_border_width=OptionsInfo(scss=True, category='summary_row', type='px', value='2px'), summary_row_border_color=OptionsInfo(scss=True, category='summary_row', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value=None), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), footnotes_marks=OptionsInfo(scss=False, category='footnotes', type='values', value='numbers'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=False), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)

\begin{table*}[!t]
\caption{Apache httpd and nginx tested with TLS Attacker reproducing the evalation of Niere et al.
TLS Attacker correctly determines code support for BoringSSL.
With OpenSSL ECH is not detected by Niere et al. due to OpenSSL ignoring errors in used ECH extensions.
Our work does not detect code support, but whether ECH is configured or not.
We do not test BoringSSL builds with ECH configured, because the webservers lack the respective bindings for BoringSSL.
}
\label{tab:tls-attacker-nginx-httpd}
\begin{tabular}{llllcccc}
\toprule
\multicolumn{6}{c}{Server Configuration} & \multicolumn{2}{c}{ECH Detected} \\
\cmidrule(lr){1-6} \cmidrule(lr){7-8}
TLS library & Webserver & Version & Released & Code Support & ECH Configured & Niere et al. & This Work \\
\midrule\addlinespace[2.5pt]
BoringSSL & nginx & 1.29.4 & 2025-12-09 & \cmark & \xmark & \cmark & \xmark \\
BoringSSL & nginx & 1.30.0 & 2026-04-14 & \cmark & \xmark & \cmark & \xmark \\
BoringSSL & nginx & 1.31.0 & 2026-05-13 & \cmark & \xmark & \cmark & \xmark \\
\midrule
OpenSSL3 & Apache httpd & 2.4.67 & 2026-05-04 & \xmark & \xmark & \xmark & \xmark \\
OpenSSL3 & nginx & 1.21.0 & 2021-05-25 & \xmark & \xmark & \xmark & \xmark \\
OpenSSL3 & nginx & 1.22.0 & 2022-05-24 & \xmark & \xmark & \xmark & \xmark \\
OpenSSL3 & nginx & 1.24.0 & 2023-04-11 & \xmark & \xmark & \xmark & \xmark \\
OpenSSL3 & nginx & 1.26.0 & 2024-04-23 & \xmark & \xmark & \xmark & \xmark \\
OpenSSL3 & nginx & 1.27.0 & 2024-05-29 & \xmark & \xmark & \xmark & \xmark \\
OpenSSL3 & nginx & 1.28.0 & 2025-04-23 & \xmark & \xmark & \xmark & \xmark \\
OpenSSL3 & nginx & 1.29.4 & 2025-12-09 & \xmark & \xmark & \xmark & \xmark \\
OpenSSL3 & nginx & 1.30.0 & 2026-04-14 & \xmark & \xmark & \xmark & \xmark \\
OpenSSL3 & nginx & 1.31.0 & 2026-05-13 & \xmark & \xmark & \xmark & \xmark \\
\midrule
OpenSSL3 with ECH \cite{d-o-23} & Apache httpd & trunk \cite{d-a-23} & 2026-03-23 & \cmark & \cmark & \cmark & \cmark \\
OpenSSL3 with ECH \cite{d-o-23} & Apache httpd & trunk \cite{d-a-23} & 2026-03-23 & \cmark & \xmark & \xmark & \xmark \\
OpenSSL3 with ECH \cite{d-o-23} & nginx & 1.29.4 & 2025-12-09 & \cmark & \cmark & \cmark & \cmark \\
OpenSSL3 with ECH \cite{d-o-23} & nginx & 1.29.4 & 2025-12-09 & \cmark & \xmark & \xmark & \xmark \\
OpenSSL3 with ECH \cite{d-o-23} & nginx & 1.30.0 & 2026-04-14 & \cmark & \cmark & \cmark & \cmark \\
OpenSSL3 with ECH \cite{d-o-23} & nginx & 1.30.0 & 2026-04-14 & \cmark & \xmark & \xmark & \xmark \\
OpenSSL3 with ECH \cite{d-o-23} & nginx & 1.31.0 & 2026-05-13 & \cmark & \cmark & \cmark & \cmark \\
OpenSSL3 with ECH \cite{d-o-23} & nginx & 1.31.0 & 2026-05-13 & \cmark & \xmark & \xmark & \xmark \\
\bottomrule
\end{tabular}

\end{table*}